# Generated by Django 4.0.4 on 2022-04-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('genres', models.CharField(choices=[('Hip-hop', 'hh'), ('Go-go', 'gg'), ('Dance', 'd'), ('Electronic', 'e'), ('Metal', 'm')], max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
