# Generated by Django 4.0.3 on 2022-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genres',
            field=models.CharField(choices=[('Hip-hop', 'Hip-hop'), ('Go-go', 'Go-go'), ('Dance', 'Dance'), ('Electronic', 'Electronic'), ('Metal', 'Metal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_2',
            field=models.CharField(choices=[('shorturl.at/mGKPY', 'Pink Room with Tree'), ('shorturl.at/dqOX4', 'Light Exhibit and Dark Male Sillhouette'), ('shorturl.at/hovB6', 'Art Gallery'), ('shorturl.at/gqCFW', 'Dinosaur Skeleton Exhibit'), ('shorturl.at/kvEHV', 'Neon Globe Exhibit'), ('shorturl.at/hkoF4', 'Street Projector Art'), ('shorturl.at/dijEP', 'Neon Hallway'), ('shorturl.at/pAFK1', 'Portrait Behind Wet Glass'), ('shorturl.at/ipqPY', 'Snakers at a Venue'), ('shorturl.at/ctBEW', "Don't Walk!"), ('shorturl.at/afuEY', 'Kaleidoscope Portrait'), ('shorturl.at/cyU47', 'Neon Entrance'), ('shorturl.at/aAHV9', 'The Matrix Aesthetic'), ('shorturl.at/etzGL', "It's Inside Us All")], max_length=1000),
        ),
    ]
