# Generated by Django 4.0.3 on 2022-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_event_genres_alter_event_img_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_2',
            field=models.CharField(choices=[('https://www.shorturl.at/mGKPY', 'Pink Room with Tree'), ('https://www.shorturl.at/dqOX4', 'Light Exhibit and Dark Male Sillhouette'), ('https://www.shorturl.at/hovB6', 'Art Gallery'), ('https://www.shorturl.at/gqCFW', 'Dinosaur Skeleton Exhibit'), ('https://www.shorturl.at/kvEHV', 'Neon Globe Exhibit'), ('https://www.shorturl.at/hkoF4', 'Street Projector Art'), ('https://www.shorturl.at/dijEP', 'Neon Hallway'), ('https://www.shorturl.at/pAFK1', 'Portrait Behind Wet Glass'), ('https://www.shorturl.at/ipqPY', 'Snakers at a Venue'), ('https://www.shorturl.at/ctBEW', "Don't Walk!"), ('https://www.shorturl.at/afuEY', 'Kaleidoscope Portrait'), ('https://www.shorturl.at/cyU47', 'Neon Entrance'), ('https://www.shorturl.at/aAHV9', 'The Matrix Aesthetic'), ('https://www.shorturl.at/etzGL', "It's Inside Us All")], max_length=1000),
        ),
    ]
