# Generated by Django 4.0.4 on 2022-04-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_event_img_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='img_2',
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.CharField(choices=[('https://i.imgur.com/lRoQdnp.jpg', 'Pink Room with Tree'), ('https://i.imgur.com/PHkcUmE.jpg', 'Light Exhibit and Dark Male Sillhouette'), ('https://i.imgur.com/7jzYmng.jpg', 'Art Gallery'), ('https://i.imgur.com/NLFOoET.jpg', 'Dinosaur Skeleton Exhibit'), ('https://i.imgur.com/1kCMaKp.jpg', 'Neon Globe Exhibit'), ('https://i.imgur.com/nlcBzWk.jpg', 'Street Projector Art'), ('https://i.imgur.com/r1oFmIj.jpg', 'Neon Hallway'), ('https://i.imgur.com/WJRdvrB.jpg', 'Portrait Behind Wet Glass'), ('https://i.imgur.com/Z2G7Rq8.jpg', 'Kaleidoscope Portrait'), ('https://i.imgur.com/BgYsieG.jpg7', 'Neon Entrance'), ('https://i.imgur.com/rggt66b.jpg', 'The Matrix Aesthetic'), ('https://i.imgur.com/x68h9hP.jpg', "It's Inside Us All")], max_length=1000),
        ),
    ]
