# Generated by Django 4.0.4 on 2022-04-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_event_img_2_alter_event_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='genres',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Meditation', 'Meditation'), ('Concert', 'Concert'), ('Exhibit', 'Exhibit'), ('Screening', 'Screening')], default='Exhibit', max_length=50),
            preserve_default=False,
        ),
    ]
