# Generated by Django 4.0.4 on 2022-04-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_event_genres_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='experience',
        ),
    ]
